-- Run with a Snowflake role allowed to create roles/users and grant access.
-- Replace the password placeholder before execution.

CREATE ROLE IF NOT EXISTS CUBE_READER;

GRANT USAGE, MONITOR ON WAREHOUSE COMPUTE_WH TO ROLE CUBE_READER;
GRANT USAGE ON DATABASE ECOMMERCE_DB TO ROLE CUBE_READER;
GRANT USAGE ON SCHEMA ECOMMERCE_DB.SILVER TO ROLE CUBE_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA ECOMMERCE_DB.SILVER TO ROLE CUBE_READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ECOMMERCE_DB.SILVER TO ROLE CUBE_READER;

CREATE USER IF NOT EXISTS CUBE_SVC
  PASSWORD = '<REPLACE_WITH_SECURE_PASSWORD>'
  DEFAULT_ROLE = CUBE_READER
  DEFAULT_WAREHOUSE = COMPUTE_WH
  MUST_CHANGE_PASSWORD = TRUE;

GRANT ROLE CUBE_READER TO USER CUBE_SVC;
