-- Run as ACCOUNTADMIN in Snowsight.

CREATE ROLE IF NOT EXISTS PULSAR_ADM;

GRANT CREATE DATABASE ON ACCOUNT TO ROLE PULSAR_ADM;
GRANT USAGE, MONITOR ON WAREHOUSE SVEY_WH_XS TO ROLE PULSAR_ADM;

GRANT ROLE PULSAR_ADM TO USER SVEY;

USE ROLE PULSAR_ADM;
CREATE DATABASE IF NOT EXISTS PULSAR_DB;
