table: product_category_name_translation
source_file: product_category_name_translation.csv
description: 'Translates the product_category_name to english.'
columns:
- name: product_category_name
  type: VARCHAR
  description: 'category name in Portuguese'
- name: product_category_name_english
  type: VARCHAR
  description: 'category name in English'
